all:
	@echo FluffOS is currently configured to use 'GNUmakefile'.  Edit 'build.FluffOS'
	@echo if this is not what you want.

.DEFAULT:
	@echo FluffOS is currently configured to use 'GNUmakefile'.  Edit 'build.FluffOS'
	@echo if this is not what you want.

nothing:

which_makefile:
	echo MakeIsMake
